version: '3.5'
services:

  investimento:
    container_name: app-investimento
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - net-driver
      - eureka_net-driver
      - credito_net-driver
      - debito_net-driver
      - prometheus_net-driver
    external_links:
      - eureka:eureka
      - credito:credito
      - debito:debito
      - prometheus:prometheus
    depends_on:
      - db
    links:
      - db
    restart: on-failure

  db:
    image: mysql
    container_name: dbinvestimento
    hostname: dbinvestimento
    restart: always
    networks:
      - net-driver
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investimentodb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  net-driver:
    driver: bridge
  eureka_net-driver:
    external: true
  credito_net-driver:
    external: true
  debito_net-driver:
    external: true
  prometheus_net-driver:
    external: true
