server:
  port: 8200
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: '${EUREKA_CONNECTION_URL:http://localhost:8761}/eureka'
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: investimento
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${DATABASE_CONNECTION_URL:jdbc:mysql://localhost:3306/investimentodb}'
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always
        data-locations: classpath:data.sql
